<a href="https://colab.research.google.com/github/KinzaaSheikh/llm_engineering_notes/blob/main/exercise1_self_attention_mechanism.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Implement attention

Build a tiny self-attention mechanism in Python/PyTorch.

X

 ↓

Q = XWq

K = XWk

V = XWv


QKᵀ

 ↓

attention scores

 ↓

softmax

 ↓

weighted V

 ↓

output

In [23]:
import numpy as np

# Toy sentence
tokens = ["The", "cat", "sat"]

# Toy embeddings
# Each token is represented by a 4-dimensional vector.
embeddings = np.array([
    [ 0.8, -0.2,  0.4,  0.1],   # The
    [ 0.7,  0.1,  0.5, -0.3],   # cat
    [-0.1,  0.2,  0.0,  0.9]    # sat
])

print("Tokens:", tokens)
print("Embedding matrix:\n", embeddings)
print("Shape:", embeddings.shape)

Tokens: ['The', 'cat', 'sat']
Embedding matrix:
 [[ 0.8 -0.2  0.4  0.1]
 [ 0.7  0.1  0.5 -0.3]
 [-0.1  0.2  0.   0.9]]
Shape: (3, 4)


In [24]:
# Simplification for this learning exercise:
# Q and K are currently the same as our embeddings.

Q = embeddings
K = embeddings

print("Q shape:", Q.shape)
print("K shape:", K.shape)

Q shape: (3, 4)
K shape: (3, 4)


In [25]:
# Compare "The" (query) with "cat" (key)

query = Q[0]
key = K[1]

score = query @ key

print("Query:", query)
print("Key:", key)
print("Dot-product score:", score)

Query: [ 0.8 -0.2  0.4  0.1]
Key: [ 0.7  0.1  0.5 -0.3]
Dot-product score: 0.71


In [26]:
# Q @ K.T calculates every query-key dot product at once.

scores = Q @ K.T

print("Raw attention scores:")
print(scores)

Raw attention scores:
[[ 0.85  0.71 -0.03]
 [ 0.71  0.84 -0.32]
 [-0.03 -0.32  0.86]]


In [27]:
# The dimensionality of each key vector
d_k = K.shape[1]

# Scale by sqrt(d_k)
scaled_scores = scores / np.sqrt(d_k)

print("d_k:", d_k)
print("sqrt(d_k):", np.sqrt(d_k))
print("\nScaled attention scores:")
print(scaled_scores)

d_k: 4
sqrt(d_k): 2.0

Scaled attention scores:
[[ 0.425  0.355 -0.015]
 [ 0.355  0.42  -0.16 ]
 [-0.015 -0.16   0.43 ]]


In [28]:
print("Embeddings:", embeddings.shape)
print("Q:", Q.shape)
print("K:", K.shape)
print("K.T:", K.T.shape)
print("Q @ K.T:", (Q @ K.T).shape)
print("Scaled scores:", scaled_scores.shape)

Embeddings: (3, 4)
Q: (3, 4)
K: (3, 4)
K.T: (4, 3)
Q @ K.T: (3, 3)
Scaled scores: (3, 3)
